### ISSUE TITLE
Example of Infi in yolov3

### ISSUE THREAD

**Issue by luyi404** [yuanmu97/InFi#1]
Hi, I just read your paper in ACM MobiCom ’22, It's a very impressive work. Now I am looking for a way to compress the YOLO model in our work, and the data in your work is attractive. 
Could you provide an example code of implementing Infi in YOLOV3? It would definitely help me a lot  : )

**Comment by yuanmu97** [comment]
I can provide an example using yolov3, which dataset do you prefer to test? If no preference I will use release a video clip used in our previous evaluations.

**Comment by luyi404** [comment]
@yuanmu97 Thanks for your reply! I don't have a preferred dataset, you can post any example, mainly because I just want to see how the Yolo model can be linked to the infi framework.

**Comment by yuanmu97** [comment]
You're welcome. This is my first time maintaining an open-source project, thank you very much for using it! I will update an example this week.

**Comment by yuanmu97** [comment]
I just updated an example with YOLOv3 on video frames, please check `examples/video*`.
I sampled 1k frames for this example and you can download it from https://drive.google.com/file/d/11kkeuLd4PRYL7rpjal5ralAqxrr-hr7W/view?usp=sharing

Hope it can help.

**Comment by luyi404** [comment]
Thanks for your example, it did help.
