### ISSUE TITLE
Ask for more example code

### ISSUE THREAD

**Issue by YourHastings** [yuanmu97/InFi#2]
Hello, sir, can you provide more example codes of some tasks such as Face Detection or Gender Classification？thank you！

**Comment by yuanmu97** [comment]
Thanks for your attention! I will update the example code for face detection this weekend.

**Comment by YourHastings** [comment]
Thank you very much. It would be better if you could give us more codes for reuse related applications. Your paper is excellent and the code is written in great detail which has deepened my understanding of input filtering technology,but I am not too clear about the specific application and implementation of REUSE.I am looking forward to hearing from you!&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mu Yuan ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuanmu97/infi] Ask for more example code (Issue #2)





 
Thanks for your attention! I will update the example code for face detection this weekend.

**Comment by yuanmu97** [comment]
OK, now I think an example for "InFi-Reuse for Gender Classification" is better for your demands.

**Comment by caiqixuan** [comment]
Hello, Sir, may I ask if you can provide the code of the "Inf-reuse for Gender Classification" part mentioned?

**Comment by yuanmu97** [comment]
I just uploaded an example for InFi-Reuse on GC task. Please see `examples/hollywood2_imgpair_preprocess.ipynb` and `examples/hollywood2_gender_infi_reuse*`.
